name: Build and Test

# Chạy workflow khi có Pull Request tới bất kỳ branch nào
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Bước 2: Thiết lập JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Thay đổi version này nếu Spring Boot của bạn sử dụng version khác
          distribution: 'temurin'

      # Bước 3: Cache thư viện Maven để tối ưu build
      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Bước 4: Build project bằng Maven
      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      # Bước 5: Chạy các bài test
      - name: Run Tests
        run: mvn test --no-transfer-progress